### PR TITLE
Initial pass on music module

### PR DESCRIPTION
**Pull request by justapieop**
WIP music module, have the abilities of play, skip, etc...

### CODE REVIEW

**Review by Serena1432 — CHANGES_REQUESTED** [review]
~~Why did you make `package_lock.json` file? Can you change the `package.json` file instead...?~~
Edit: I saw the changes in the next commit. Sorry for misunderstanding.

**Review by Serena1432 — APPROVED** [review]

**Review by Serena1432 — APPROVED** [review]

**Comment by justapieop** [comment]
well, i made the package-lock to keep the version of the dependencies i'm using as it don't make dependencies be installed as an other version which i don't want to
but if you don't want to create a package-lock.json, why don't you just ignore it

**Comment by justapieop** [comment]
lmao git problems

**Comment by justapieop** [comment]
Closed Due to problems with discord opus

**Pull request closed without merging**
